### ISSUE TITLE
stuck with homework

### ISSUE THREAD

**Issue by evainga** [evainga/Timeline#7]
@mle-enso do you have a hint for my failing tests? i am stuck...

**Comment by mle-enso** [comment]
What exactly is your concern?

**Comment by mle-enso** [comment]
Ah i see... compiler error. See my comment on your last commit.

Didn't you see the compiler error in your IDE or mvn run?

```[ERROR] /home/marco/dev/git/Timeline/src/test/java/de/timeline/TimelineServiceTest.java:[41,76] void cannot be dereferenced```

**Comment by mle-enso** [comment]
Always remember: chained method calls like ```timelineService.createEvent(sommer).getAllEvents()``` will only work if the latter method exists on the object returned by the former method call.
Ask yourself: What is returned by createEvent and does this object have a method getAllEvents?

**Comment by evainga** [comment]
I read the message, but didn't know how to solve it. Finally, I got it now - at least for my createEvent Test...

**Comment by evainga** [comment]
such a beauty in a green test... :)

**Comment by mle-enso** [comment]
Yeah but it would be even greener to have the whole build green!

**Comment by mle-enso** [comment]
Do not worry if you can not solve the TimelineController test yet. Just write pseudo code and add comments that denote what you would like to do.
For solving it on your own we need the concept of mocks in our test code. We will discuss it tomorrow. However it is important to learn about the principles of loose coupling between controller and service and how to test this.

**Comment by evainga** [comment]
my guess is that a method like setupDb() in TimelineServiceTest is missing, but nothing in that way that I tried was working... so I am curious about tomorrow

**Comment by mle-enso** [comment]
We are on the unit test level. We want to test the TimelineController, so nothing in its dependent services like TimelineService should interfer our TimelineControllerTest, so setupDb is out.

It is rather the way how your TimelineController finds a correct instance of TimelineService while testing. In production the Spring Framework does the magic via ```@Autowired```. However this only works in integration tests. In unit tests like TimelineControllerTest we have to use ```@InjectMocks``` and ```@Mock```, details tomorrow.

Do you remember the Mockito tutorial, I've sent to you?
http://static.javadoc.io/org.mockito/mockito-core/2.7.1/org/mockito/Mockito.html#mock_annotation
